#!/usr/bin/env bash
# Deploy Apollo Reborn self-hosted push backend to Azure via Terraform.
#
# Idempotent: safe to re-run. Terraform tracks every resource in
# ./terraform.tfstate, so re-applies converge instead of duplicating. The
# Postgres password and registration token are generated by random_password
# resources and persist in state — re-applies do NOT rotate them.
#
# Required external state:
#   - $HOME/Code/side/ios/AuthKey_<KEY_ID>.p8  (your APNs auth key)
#   - `az login` session (Terraform's azurerm provider reuses az CLI auth)
#   - terraform >= 1.6 installed (brew install terraform)
#
# Required inputs (set as env vars or this script will prompt):
#   APPLE_APNS_TOPIC   bundle ID of your sideloaded Apollo build
#   APPLE_TEAM_ID      10-char Apple Developer team ID
#   APPLE_KEY_ID       10-char APNs auth key ID
#   APPLE_KEY_PATH     full path to your AuthKey_XXXXXXXXXX.p8 file
#   REDDIT_CLIENT_ID   Reddit OAuth client ID
#   REDDIT_USER_AGENT  must include "(by /u/<your-reddit-username>)"
# Optional:
#   REDDIT_CLIENT_SECRET   blank for installed-app credentials
#   AZURE_LOCATION         default: southcentralus
#   AZURE_SUBSCRIPTION     default: currently selected `az account` subscription
#   RG_NAME                default: apollo-backend-rg
#   APPLE_APNS_SANDBOX     default: true (required for dev-signed sideloads)
#   REDDIT_REDIRECT_URI    default: apollo://reddit-oauth

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

: "${AZURE_LOCATION:=southcentralus}"
: "${RG_NAME:=apollo-backend-rg}"
: "${APPLE_APNS_SANDBOX:=true}"
: "${REDDIT_REDIRECT_URI:=apollo://reddit-oauth}"

# --- Pretty output -----------------------------------------------------------

c_blue=$'\033[1;34m'
c_green=$'\033[1;32m'
c_yellow=$'\033[1;33m'
c_red=$'\033[1;31m'
c_dim=$'\033[2m'
c_reset=$'\033[0m'

log()  { echo -e "${c_blue}==>${c_reset} $*"; }
ok()   { echo -e "${c_green}✓${c_reset} $*"; }
warn() { echo -e "${c_yellow}!${c_reset} $*" >&2; }
die()  { echo -e "${c_red}✗${c_reset} $*" >&2; exit 1; }

# --- Sanity checks -----------------------------------------------------------

command -v terraform >/dev/null || die "Terraform not installed. Run: brew install terraform"
command -v az        >/dev/null || die "Azure CLI not installed. Run: brew install azure-cli"

if ! az account show >/dev/null 2>&1; then
  die "Not signed in to Azure CLI. Run: az login"
fi

if [[ -n "${AZURE_SUBSCRIPTION:-}" ]]; then
  log "Setting active subscription: ${AZURE_SUBSCRIPTION}"
  az account set --subscription "${AZURE_SUBSCRIPTION}"
fi

# Terraform's azurerm v4 provider requires ARM_SUBSCRIPTION_ID. Pull it from
# the active az subscription. Tenant + auth come from the az CLI session.
ARM_SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
ARM_TENANT_ID="$(az account show --query tenantId -o tsv)"
SUB_NAME="$(az account show --query name -o tsv)"
export ARM_SUBSCRIPTION_ID ARM_TENANT_ID

log "Subscription: ${SUB_NAME} (${ARM_SUBSCRIPTION_ID})"
log "Resource group: ${RG_NAME} (${AZURE_LOCATION})"

# --- Provider registration --------------------------------------------------
# Container Apps and Postgres Flex need their providers registered on first
# use of a subscription. Idempotent; near-instant if already registered.

log "Ensuring required Azure providers are registered…"
for ns in Microsoft.App Microsoft.OperationalInsights Microsoft.DBforPostgreSQL; do
  STATE=$(az provider show --namespace "${ns}" --query registrationState -o tsv)
  if [[ "${STATE}" != "Registered" ]]; then
    warn "Registering provider ${ns} (current state: ${STATE})…"
    az provider register --namespace "${ns}" --wait -o none
  fi
done
ok "All providers registered"

# --- Required inputs --------------------------------------------------------

prompt_var() {
  local var="$1" prompt="$2" secret="${3:-}" input
  if [[ -n "${!var:-}" ]]; then
    echo "${!var}"
    return
  fi
  if [[ "${secret}" == "secret" ]]; then
    read -rsp "${prompt}: " input
    echo >&2
  else
    read -rp "${prompt}: " input
  fi
  echo "${input}"
}

APPLE_APNS_TOPIC="$(prompt_var APPLE_APNS_TOPIC  'Bundle ID (APPLE_APNS_TOPIC)')"
APPLE_TEAM_ID="$(prompt_var   APPLE_TEAM_ID      'Apple Team ID (10 chars)')"
APPLE_KEY_ID="$(prompt_var    APPLE_KEY_ID       'APNs Key ID (10 chars)')"
APPLE_KEY_PATH="$(prompt_var  APPLE_KEY_PATH     'Path to AuthKey_*.p8 file')"
REDDIT_USER_AGENT="$(prompt_var REDDIT_USER_AGENT 'Reddit User-Agent (must include "(by /u/<name>)")')"

[[ -f "${APPLE_KEY_PATH}" ]] || die "APNs key file not found: ${APPLE_KEY_PATH}"
[[ "${APPLE_APNS_TOPIC}" != "com.christianselig.Apollo" ]] || die "APPLE_APNS_TOPIC must be your custom bundle ID, not com.christianselig.Apollo (Reddit WAF blocks the latter in UAs)."

# Reddit OAuth — prompted via read -s; never written to disk except inside the
# Terraform state file (which is gitignored and locked to 0600 below).
REDDIT_CLIENT_ID="$(prompt_var REDDIT_CLIENT_ID 'Reddit Client ID' secret)"
if [[ -z "${REDDIT_CLIENT_SECRET:-}" ]]; then
  read -rsp 'Reddit Client Secret (blank for installed-app credentials): ' REDDIT_CLIENT_SECRET || true
  echo
fi

# --- Wire inputs through to Terraform ---------------------------------------

APPLE_KEY_PEM="$(cat "${APPLE_KEY_PATH}")"

export TF_VAR_resource_group_name="${RG_NAME}"
export TF_VAR_location="${AZURE_LOCATION}"
export TF_VAR_apple_apns_topic="${APPLE_APNS_TOPIC}"
export TF_VAR_apple_team_id="${APPLE_TEAM_ID}"
export TF_VAR_apple_key_id="${APPLE_KEY_ID}"
export TF_VAR_apple_key_pem="${APPLE_KEY_PEM}"
export TF_VAR_apple_apns_sandbox="${APPLE_APNS_SANDBOX}"
export TF_VAR_reddit_client_id="${REDDIT_CLIENT_ID}"
export TF_VAR_reddit_client_secret="${REDDIT_CLIENT_SECRET:-}"
export TF_VAR_reddit_redirect_uri="${REDDIT_REDIRECT_URI}"
export TF_VAR_reddit_user_agent="${REDDIT_USER_AGENT}"

# --- terraform init + apply -------------------------------------------------

log "terraform init"
terraform init -upgrade -input=false

log "terraform apply (5–8 minutes on first deploy)"
terraform apply -auto-approve -input=false

# Lock down state — it contains every generated secret in plaintext.
chmod 600 terraform.tfstate terraform.tfstate.backup 2>/dev/null || true

# --- Read outputs -----------------------------------------------------------

API_FQDN="$(terraform output -raw api_fqdn)"
HEALTH_URL="$(terraform output -raw health_url)"
REG_TOKEN="$(terraform output -raw registration_secret)"
MIGRATION_JOB="$(terraform output -raw migration_job_name)"
RG_OUT="$(terraform output -raw resource_group_name)"

# --- Run schema bootstrap ---------------------------------------------------

log "Running schema-bootstrap job: ${MIGRATION_JOB}"
EXEC_NAME="$(az containerapp job start \
  --name "${MIGRATION_JOB}" \
  --resource-group "${RG_OUT}" \
  --query name -o tsv)"
ok "Job started: ${EXEC_NAME}"

log "Waiting for migration job to complete (typical: 30–60s)…"
for i in $(seq 1 60); do
  STATUS="$(az containerapp job execution show \
    --job-name "${MIGRATION_JOB}" \
    --resource-group "${RG_OUT}" \
    --name "${EXEC_NAME}" \
    --query 'properties.status' -o tsv 2>/dev/null || echo Pending)"
  case "${STATUS}" in
    Succeeded) ok "Migration job succeeded"; break ;;
    Failed|Degraded|Stopped)
      warn "Migration job ended with status: ${STATUS}"
      warn "Inspect with:"
      warn "  az containerapp job execution show -g ${RG_OUT} --job-name ${MIGRATION_JOB} --name ${EXEC_NAME}"
      die "Migration failed; check the Azure portal Container Apps logs."
      ;;
    *) printf '\r  …status: %s (poll %d/60)   ' "${STATUS}" "${i}"; sleep 5 ;;
  esac
done
echo

# --- Health check -----------------------------------------------------------

log "Hitting health endpoint: ${HEALTH_URL}"
for i in $(seq 1 30); do
  if curl -fsS --max-time 5 "${HEALTH_URL}" 2>/dev/null | grep -q 'available'; then
    ok "Health endpoint responding: $(curl -fsS "${HEALTH_URL}")"
    break
  fi
  printf '\r  …warming up (poll %d/30)   ' "${i}"
  sleep 4
done
echo

# --- Final summary ----------------------------------------------------------

cat <<EOF

${c_green}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${c_reset}
${c_green}  Apollo Reborn backend deployed${c_reset}
${c_green}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${c_reset}

  ${c_blue}Backend URL${c_reset}          https://${API_FQDN}
  ${c_blue}Health endpoint${c_reset}      ${HEALTH_URL}
  ${c_blue}Registration token${c_reset}   ${REG_TOKEN}
  ${c_dim}(also available via: terraform output -raw registration_secret)${c_reset}

  ${c_yellow}Next steps on your iPhone:${c_reset}
    1. Apollo → Settings → Custom API → Notification Backend
    2. Backend URL:        https://${API_FQDN}
    3. Registration Token: (token printed above)
    4. Tap ${c_blue}Test Connection${c_reset} — expect a green check.
    5. Force-quit Apollo, reopen it, sign in / re-sign in to your Reddit
       account so device + account rows land in Postgres.

  ${c_yellow}Verify end-to-end:${c_reset}
    ./verify.sh

  ${c_dim}Tear down everything:${c_reset}
    ${c_dim}./teardown.sh${c_reset}

EOF
