output "resource_group_name" {
  description = "Resource group containing the entire deployment."
  value       = azurerm_resource_group.main.name
}

output "api_fqdn" {
  description = "Public FQDN of the API container app. Used as Notification Backend URL in the tweak."
  value       = azurerm_container_app.api.ingress[0].fqdn
}

output "api_url" {
  description = "Backend URL to paste into Settings → Custom API → Notification Backend."
  value       = "https://${azurerm_container_app.api.ingress[0].fqdn}"
}

output "health_url" {
  description = "Health endpoint. Should return {\"status\":\"available\"}."
  value       = "https://${azurerm_container_app.api.ingress[0].fqdn}/v1/health"
}

output "registration_secret" {
  description = "Token to paste into Settings → Custom API → Registration Token."
  value       = random_password.registration_secret.result
  sensitive   = true
}

output "postgres_server_fqdn" {
  description = "Postgres Flex Server FQDN. Useful for ad-hoc psql sessions (requires temporarily allowing your client IP via the firewall)."
  value       = azurerm_postgresql_flexible_server.main.fqdn
}

output "postgres_admin_username" {
  description = "Postgres admin login name."
  value       = local.pg_admin_user
}

output "postgres_admin_password" {
  description = "Postgres admin password (generated by Terraform). Persisted in state; re-applies do not rotate."
  value       = random_password.postgres.result
  sensitive   = true
}

output "postgres_database_name" {
  description = "Application database name."
  value       = local.pg_database_name
}

output "migration_job_name" {
  description = "Container Apps Job for schema bootstrap. Run with: az containerapp job start --name <this> -g <rg>"
  value       = azurerm_container_app_job.migrate.name
}

output "container_app_environment_name" {
  description = "Container Apps environment that holds all 9 apps + the migration job."
  value       = azurerm_container_app_environment.main.name
}
